id <- c(1)
sex <- c("female")
age <- c(20)
exp <- c("zero")
answer <- c("As a 20-year-old girl with no dating experience, I would be quite nervous and excited about my first date. For me to want another date with him, my partner's behavior would need to make me feel comfortable and valued. He should listen actively when I speak, showing genuine interest in what I have to say. This means maintaining eye contact, nodding, and asking follow-up questions. It would make me feel heard and appreciated. Simple gestures like holding the door open, saying please and thank you, and being considerate of my comfort would go a long way. It shows he has good manners and respects me. A good sense of humor can break the ice and make the date enjoyable. If he can make me laugh and we can share some light-hearted moments, it would help ease my nerves and create a positive atmosphere. Being himself and not trying to impress me with exaggerated stories or false pretenses is important. Authenticity is attractive and helps build trust from the start. Small acts of kindness, like asking if I’m comfortable or if I need anything, show that he cares about my well-being. Thoughtfulness in conversation, like remembering small details I mentioned earlier, would also be impressive. Finding common ground and shared interests would make the conversation flow more naturally and make me feel more connected to him. It would also give us something to look forward to discussing or doing together in the future. If he exhibits these behaviors, I would feel more at ease and excited about the possibility of getting to know him better on another date.")

girl_1 <- data.frame(id, sex, age, exp, answer)
girl_2 <- data.frame(
  id = 2,
  sex = "female",
  age = 23,
  exp = "some",
  answer = "As a 23-year-old girl with some dating experience, I have a clearer idea of what I value in a partner and what behaviors make a date enjoyable and promising for a future relationship. He should be able to hold a meaningful and engaging conversation. This means not just talking about himself but also showing interest in my thoughts, opinions, and experiences. A good balance of talking and listening is crucial. Confidence is attractive, but it should be balanced with humility. He should be comfortable in his own skin and able to express himself without coming across as arrogant or dismissive. He should be respectful of my personal space and boundaries. This includes being mindful of physical touch and not pushing for more than I’m comfortable with. Respecting my boundaries shows that he values my comfort and consent. Small gestures, like asking if I’m enjoying myself or if I need anything, show that he is considerate and attentive to my needs. Thoughtfulness can also be reflected in the planning of the date, such as choosing a place that aligns with my interests. A positive and optimistic outlook can make the date more enjoyable. If he can handle minor inconveniences with grace and maintain a cheerful demeanor, it creates a pleasant atmosphere. Discovering common values and interests can create a deeper connection. Whether it’s a shared passion for a hobby, similar life goals, or aligned values, these commonalities can be the foundation for a strong relationship. Basic manners and politeness are essential. This includes being punctual, treating service staff with respect, and showing general courtesy throughout the date. A good sense of humor can make the date fun and memorable. If he can make me laugh and we can share some light-hearted moments, it helps build a connection and makes me look forward to spending more time with him. If he demonstrates these behaviors, I would feel more confident and excited about the potential for a second date, knowing that he respects me and that we have the potential for a meaningful connection."
)
girl_3 <- data.frame(
  id = 3,
  sex = "female",
  age = 25,
  exp = "much",
  answer = "As a 25-year-old girl with considerable dating experience, I have a refined sense of what I’m looking for in a partner and what behaviors make a first date successful. He should be genuine and honest about who he is. I appreciate someone who is comfortable in their own skin and doesn’t feel the need to put on a facade. Authenticity builds trust and sets a solid foundation for any potential relationship. He should be able to read the room and respond appropriately to the emotional cues. This includes being empathetic, understanding, and supportive. Emotional intelligence is crucial for navigating the complexities of relationships. He should respect my independence and understand that I have my own life, interests, and commitments. This means not being overly clingy or possessive and appreciating that a healthy relationship involves two individuals with their own identities. Effective communication is key. He should be able to express his thoughts and feelings clearly and listen actively to mine. This includes being open to discussing both light-hearted topics and more serious matters. It’s important that we have aligned values and long-term goals. Whether it’s views on family, career aspirations, or lifestyle choices, having common ground in these areas can indicate compatibility. He should treat me and others with respect and consideration. This includes being polite to service staff, showing up on time, and being mindful of my comfort and preferences throughout the date. Confidence is attractive, especially when paired with ambition and a clear sense of direction in life. I appreciate someone who is driven and has goals they are actively working towards. A good sense of humor can make the date enjoyable and memorable. If he can make me laugh and we can share some fun moments, it helps create a positive connection. Small gestures that show he’s paying attention to me and my interests can be very endearing. Whether it’s remembering something I mentioned earlier or planning a date that aligns with my preferences, thoughtfulness goes a long way. If he exhibits these behaviors, I would feel optimistic about the potential for a meaningful and fulfilling relationship, making me eager to go on another date with him."
)
girl <- rbind(girl_1,girl_2,girl_3)

boy_1 <- data.frame(
  id = 4,
  sex = "male",
  age = 20,
  exp = "zero",
  answer = "As a 20-year-old boy with no dating experience, I would be both nervous and excited about my first date. For me to want another date with her, my partner's behavior would need to make me feel comfortable and appreciated. She should be warm and welcoming, making it easy for me to relax and be myself. A friendly demeanor helps break the ice and sets a positive tone for the date. She should show genuine interest in getting to know me by asking questions and actively listening to my responses. This makes me feel valued and appreciated. A good sense of humor can make the date fun and enjoyable. If she can make me laugh and we can share some light-hearted moments, it would help ease my nerves and create a memorable experience. Basic manners and politeness are important. This includes being considerate of my feelings, not interrupting when I speak, and showing general courtesy throughout the date. Being herself and not trying to impress me with exaggerated stories or false pretenses is important. Authenticity is attractive and helps build trust from the start. Small acts of kindness, like asking if I’m comfortable or if I need anything, show that she cares about my well-being. Thoughtfulness in conversation, like remembering small details I mentioned earlier, would also be impressive. Finding common ground and shared interests would make the conversation flow more naturally and make me feel more connected to her. It would also give us something to look forward to discussing or doing together in the future. A positive and optimistic outlook can make the date more enjoyable. If she can handle minor inconveniences with grace and maintain a cheerful demeanor, it creates a pleasant atmosphere. If she exhibits these behaviors, I would feel more at ease and excited about the possibility of getting to know her better on another date."
)

boy_2 <- data.frame(
  id = 5,
  sex = "male",
  age = 23,
  exp = "some",
  answer = "As a 23-year-old boy with some dating experience, I have a better understanding of what makes a date enjoyable and what behaviors I appreciate in a partner. She should be able to hold an interesting and engaging conversation. This means not just talking about herself but also showing genuine interest in my thoughts, opinions, and experiences. A good balance of talking and listening is crucial. Confidence is attractive, but it should be balanced with authenticity. She should be comfortable being herself and not feel the need to put on a facade. Authenticity builds trust and makes the interaction more genuine. She should be respectful of my personal space and boundaries. This includes being mindful of physical touch and not pushing for more than I’m comfortable with. Respecting my boundaries shows that she values my comfort and consent. Small gestures, like asking if I’m enjoying myself or if I need anything, show that she is considerate and attentive to my needs. Thoughtfulness can also be reflected in the planning of the date, such as choosing a place that aligns with my interests. A positive and optimistic outlook can make the date more enjoyable. If she can handle minor inconveniences with grace and maintain a cheerful demeanor, it creates a pleasant atmosphere. A good sense of humor can also make the date fun and memorable. Discovering common values and interests can create a deeper connection. Whether it’s a shared passion for a hobby, similar life goals, or aligned values, these commonalities can be the foundation for a strong relationship. Basic manners and politeness are essential. This includes being punctual, treating service staff with respect, and showing general courtesy throughout the date. Ambition and a clear sense of direction in life are attractive qualities. I appreciate someone who is driven and has goals they are actively working towards. If she demonstrates these behaviors, I would feel confident and excited about the potential for a meaningful and fulfilling relationship, making me eager to go on another date with her."
)

boy_3 <- data.frame(
  id = 6,
  sex = "male",
  age = 25,
  exp = "high",
  answer = "As a 25-year-old boy with considerable dating experience, I have a clear understanding of what I value in a partner and what behaviors make a first date successful. She should be genuine and honest about who she is. I appreciate someone who is comfortable in their own skin and doesn’t feel the need to put on a facade. Authenticity builds trust and sets a solid foundation for any potential relationship. She should be able to read the room and respond appropriately to emotional cues. This includes being empathetic, understanding, and supportive. Emotional intelligence is crucial for navigating the complexities of relationships. She should respect my independence and understand that I have my own life, interests, and commitments. This means not being overly clingy or possessive and appreciating that a healthy relationship involves two individuals with their own identities. Effective communication is key. She should be able to express her thoughts and feelings clearly and listen actively to mine. This includes being open to discussing both light-hearted topics and more serious matters. It’s important that we have aligned values and long-term goals. Whether it’s views on family, career aspirations, or lifestyle choices, having common ground in these areas can indicate compatibility. She should treat me and others with respect and consideration. This includes being polite to service staff, showing up on time, and being mindful of my comfort and preferences throughout the date. Confidence is attractive, especially when paired with ambition and a clear sense of direction in life. I appreciate someone who is driven and has goals they are actively working towards. A good sense of humor can make the date enjoyable and memorable. If she can make me laugh and we can share some fun moments, it helps create a positive connection. Small gestures that show she’s paying attention to me and my interests can be very endearing. Whether it’s remembering something I mentioned earlier or planning a date that aligns with my preferences, thoughtfulness goes a long way. If she exhibits these behaviors, I would feel optimistic about the potential for a meaningful and fulfilling relationship, making me eager to go on another date with her."
)

boy <- rbind(boy_1,boy_2,boy_3)
data <- rbind(girl,boy)

write.csv(data, "data_raw/firstDate.csv")
